import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { zipSync, strToU8 } from 'fflate';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1360, height: 1000 } });
await context.addInitScript(()=>{
  const port={id:'test-piano',name:'Test-Digitalpiano',state:'connected',onmidimessage:null};
  const access={inputs:new Map([[port.id,port]]),onstatechange:null};
  window.__midiFake={port,access,send:(...data)=>port.onmidimessage?.({data:new Uint8Array(data)})};
  Object.defineProperty(navigator,'requestMIDIAccess',{value:async()=>access,configurable:true});
});
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('test-results', { recursive: true });
const state = () => page.evaluate(() => { const a=window.__practice; const e=a.engine; return { busy:a.busy, beat:e?.beat, expected:e?.expected, finished:e?.finished, collected:[...(e?.collected??[])], measures:e?.score.measures, notes:e?.score.notes, playing:e?.playing, mode:e?.mode, settings:e?.settings, title:e?.score.title }; });
const ready = async () => { await page.waitForFunction(() => window.__practice?.engine && !window.__practice.busy && (!window.__practice.progress || window.__practice.progress.ready), null, {timeout:60000}); };
try {
  await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'}); await ready();
  let s=await state(); assert.equal(s.measures.length,8); assert.equal(s.notes[0].midi,60,'MusicXML C4 muss MIDI 60 sein');
  assert.equal(s.measures.at(-1).end,32); assert.equal(s.notes.find(n=>n.start===26 && n.midi===60).end,32,'Haltebogen über Taktgrenze');
  assert.equal(await page.evaluate(()=>window.__practice.view.osmd.cursor.Iterator.CurrentSourceTimestamp.RealValue*4),0,'Cursor am ersten Einsatz');
  assert.equal(await page.locator('#score svg').count()>0,true);
  assert.equal(await page.locator('#warnings').isVisible(),false,'Doppelte Tempoangabe in einem direction-Element ist ein Ereignis');
  assert.equal(await page.locator('.practice-panel #step').count(),1,'Übemodus am Notenpult');
  assert.equal(await page.locator('.practice-panel [data-hand="right"]').count(),1,'Handwahl am Notenpult');
  assert.equal(await page.locator('#midi-settings').getAttribute('open'),null,'Optionale Einstellungen beginnen eingeklappt');
  await page.locator('#volume').press('End'); assert.equal(await page.locator('#volume-value').textContent(),'100 %');
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.locator('#step').click();
  assert.deepEqual((await state()).expected,[60,48]);
  await page.keyboard.down('a'); assert.deepEqual((await state()).collected,[60]);
  await page.keyboard.down('a'); assert.deepEqual((await state()).collected,[60]);
  await page.keyboard.up('a');
  await page.locator('[data-midi="61"]').click(); assert.equal((await state()).beat,0); assert.deepEqual((await state()).collected,[60]);
  await page.locator('[data-midi="48"]').click(); assert.equal((await state()).beat,1);
  assert.equal(await page.evaluate(()=>window.__practice.view.osmd.cursor.Iterator.CurrentSourceTimestamp.RealValue*4),1,'Cursor folgt dem Schritt');
  let count=0;
  while (!(s=await state()).finished && count++<100) for (const midi of s.expected) await page.locator(`[data-midi="${midi}"]`).click();
  assert.equal((await state()).finished,true,'Gesamtes Beispiel durch Schrittmodus');
  await page.locator('#listen').click(); await page.locator('#play').click();
  await page.waitForFunction(()=>window.__practice.audio.diagnostics.ready && window.__practice.engine.playing);
  const diagnostics=await page.evaluate(()=>window.__practice.audio.diagnostics);assert.equal(diagnostics.ready,true);assert.equal(diagnostics.buffers,30);assert.equal(diagnostics.context,'running');
  await page.waitForFunction(()=>window.__practice.audio.diagnostics.level>.001); // Signal am tatsächlichen Audioausgang.
  await page.waitForFunction(()=>window.__practice.engine.beat>.3);
  assert.equal(await page.locator('.piano-key.sounding').count()>0,true);
  await page.locator('#play').click(); const paused=(await state()).beat; await page.waitForTimeout(150); assert.equal((await state()).beat,paused);
  await page.locator('#play').click(); await page.waitForFunction(p=>window.__practice.engine.beat>p,paused); await page.locator('#play').click();
  const rms=await page.evaluate(async()=>{const c=new AudioContext(); const b=await c.decodeAudioData(await (await fetch('/piano/C4.mp3')).arrayBuffer());const data=b.getChannelData(0);const value=Math.sqrt(data.reduce((a,x)=>a+x*x,0)/data.length);await c.close();return value;});
  assert.ok(rms>.001,'Klaviersample enthält hörbares Signal');
  await page.locator('#from').selectOption('1'); await page.locator('#to').selectOption('1'); await page.locator('#loop').check(); await page.locator('#step').click();
  const initial=(await state()).beat; let loops=0;
  while(loops++<20){s=await state();for(const midi of s.expected)await page.locator(`[data-midi="${midi}"]`).click(); if((await state()).beat===initial)break;}
  assert.equal((await state()).finished,false); assert.equal((await state()).beat,initial);
  await page.locator('#file').setInputFiles({name:'kaputt.xml',mimeType:'application/xml',buffer:Buffer.from('<kaputt>')});
  await page.waitForFunction(()=>document.querySelector('#message').classList.contains('error')); assert.equal((await state()).title,'Kleine Klavierzeit');
  const example=await readFile('public/example.musicxml');
  const mxl=zipSync({'META-INF/container.xml':strToU8('<container><rootfiles><rootfile full-path="score.musicxml" media-type="application/vnd.recordare.musicxml+xml"/></rootfiles></container>'),'score.musicxml':example});
  await page.locator('#file').setInputFiles({name:'beispiel.mxl',mimeType:'application/vnd.recordare.musicxml',buffer:Buffer.from(mxl)}); await ready(); assert.equal((await state()).measures.length,8);
  await page.locator('#file').setInputFiles('tests/fixtures/robust.musicxml'); await ready(); s=await state();
  assert.deepEqual(s.measures.map(m=>[m.start,m.end]),[[0,1],[1,5],[5,8]],'Auftakt und wechselnde Taktart');
  assert.equal(s.notes.find(n=>n.midi===66).end,2.5,'Punktierung und Vorzeichen');
  assert.ok(Math.abs(s.notes.find(n=>n.start===2.5).end-17/6)<1e-7,'Triolendauer');
  assert.equal(s.notes.find(n=>n.midi===48).end,8,'Gebundener Ton über Takt- und divisions-Wechsel');
  assert.equal(s.notes.filter(n=>n.start===1).length,3,'Mehrere Stimmen und Notensysteme');
  await page.locator('#zoom').selectOption('1.25'); assert.equal(await page.locator('#score svg').count()>0,true);
  await page.evaluate(xml=>{const transfer=new DataTransfer();transfer.items.add(new File([xml],'drop.musicxml',{type:'application/xml'}));document.querySelector('#dropzone').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));},example.toString());await ready();assert.equal((await state()).title,'Kleine Klavierzeit');
  const robust=(await readFile('tests/fixtures/robust.musicxml')).toString();
  await page.evaluate(async({example,robust})=>{const {loadXML}=await import('/src/main.ts');await Promise.all([loadXML(robust),loadXML(example)]);},{example:example.toString(),robust});await ready();assert.equal((await state()).title,'Kleine Klavierzeit','Neuester Import gewinnt bei parallelen Ladeversuchen');
  await page.locator('#example').click(); await ready();
  await page.locator('#loop').uncheck();
  await page.locator('#step').click(); await page.locator('[data-hand="right"]').click(); assert.deepEqual((await state()).expected,[60]);
  await page.locator('[data-hand="left"]').click(); assert.deepEqual((await state()).expected,[48]);
  await page.locator('.mapping summary').click(); await page.locator('#left-staff').selectOption('0'); assert.deepEqual((await state()).expected,[60]);
  await page.locator('#left-staff').selectOption('1'); await page.locator('[data-hand="both"]').click(); assert.deepEqual((await state()).expected,[60,48]);
  await page.locator('#listen').click();
  await page.locator('#midi-settings summary').click(); await page.locator('#midi-connect').click(); assert.match(await page.locator('#midi-status').textContent(),/Verbunden: Test-Digitalpiano/);
  await page.locator('#step').click(); await page.evaluate(()=>{window.__midiFake.send(0x92,60,127);window.__midiFake.send(0x93,48,100);}); assert.equal((await state()).beat,1);
  await page.evaluate(()=>{window.__midiFake.send(0x82,60,50);window.__midiFake.send(0x93,48,0);}); assert.deepEqual(await page.evaluate(()=>window.__practice.input.pressed),[]);
  await page.evaluate(()=>{window.__midiFake.send(0x90,62,100);window.__midiFake.send(0x90,62,100);}); assert.equal((await state()).beat,2);
  await page.evaluate(()=>{window.__midiFake.port.state='disconnected';window.__midiFake.access.onstatechange();}); assert.match(await page.locator('#midi-status').textContent(),/Kein MIDI/); assert.deepEqual(await page.evaluate(()=>window.__practice.input.pressed),[]);
  await page.locator('#listen').click();
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(()=>{const key=document.querySelector('[data-midi="60"]').getBoundingClientRect();const area=document.querySelector('#keyboard-scroll').getBoundingClientRect();return key.left>=area.left && key.right<=area.right;});
  await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Keine horizontale Seitenausdehnung');
  assert.equal(await page.locator('.practice-panel').evaluate(el=>el.getBoundingClientRect().top < document.querySelector('.controls').getBoundingClientRect().top),true,'Noten und Wiedergabe stehen mobil vor den Einstellungen');
  assert.equal(await page.locator('[data-midi="60"]').evaluate(el=>{const key=el.getBoundingClientRect();const area=document.querySelector('#keyboard-scroll').getBoundingClientRect();return key.left>=area.left && key.right<=area.right;}),true,'Computerbelegung bleibt nach Größenwechsel sichtbar');
  for (const width of [320,768,1024,1920]) {
    await page.setViewportSize({width,height:900});await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`Keine horizontale Seitenausdehnung bei ${width} px`);
    assert.equal(await page.locator('.practice-settings').evaluate(el=>el.scrollWidth<=el.clientWidth),true,`Überegler passen bei ${width} px`);
  }
  const touchContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const touchPage=await touchContext.newPage();await touchPage.goto('http://127.0.0.1:5173');await touchPage.waitForFunction(()=>window.__practice?.engine&&!window.__practice.busy);await touchPage.locator('#step').tap();await touchPage.locator('[data-midi="48"]').tap();await touchPage.locator('[data-midi="60"]').tap();assert.equal(await touchPage.evaluate(()=>window.__practice.engine.beat),1);await touchContext.close();
  const storageContext=await browser.newContext({viewport:{width:1360,height:1000}});await storageContext.route('**/piano/*.mp3',async route=>{await new Promise(done=>setTimeout(done,300));await route.continue();});const storagePage=await storageContext.newPage();
  const storageReady=()=>storagePage.waitForFunction(()=>window.__practice?.engine&&!window.__practice.busy&&window.__practice.progress?.ready);
  await storagePage.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});await storageReady();
  await storagePage.locator('#play').click();await storagePage.locator('#reset').click();await storagePage.waitForFunction(()=>window.__practice.audio.diagnostics.ready);assert.equal(await storagePage.evaluate(()=>window.__practice.engine.playing),false,'Zurücksetzen verhindert verspäteten Start während des Klangladens');
  await storagePage.locator('#step').click();
  await storagePage.locator('[data-midi="61"]').click();await storagePage.locator('[data-midi="48"]').click();await storagePage.locator('[data-midi="60"]').click();
  assert.match(await storagePage.locator('#completed-progress').textContent(),/^1 \/ /);assert.equal(await storagePage.locator('#mistakes-progress').textContent(),'1');
  await storagePage.locator('[data-hand="right"]').click();assert.match(await storagePage.locator('#completed-progress').textContent(),/^0 \/ /);await storagePage.locator('[data-midi="60"]').click();
  await storagePage.locator('#tempo').press('Home');await storagePage.locator('#tempo').press('ArrowRight');
  await storagePage.evaluate(()=>window.__practice.progress.flush());await storagePage.reload({waitUntil:'domcontentloaded'});await storageReady();
  assert.equal(await storagePage.evaluate(()=>window.__practice.engine.settings.hand),'right');assert.equal(await storagePage.evaluate(()=>window.__practice.engine.settings.bpm),31);assert.match(await storagePage.locator('#completed-progress').textContent(),/^1 \/ /);assert.equal(await storagePage.locator('#mistakes-progress').textContent(),'0');
  await storagePage.locator('[data-hand="both"]').click();assert.equal(await storagePage.locator('#mistakes-progress').textContent(),'1');assert.match(await storagePage.locator('#completed-progress').textContent(),/^1 \/ /);
  storagePage.once('dialog',dialog=>dialog.accept());await storagePage.locator('#progress-settings summary').click(); await storagePage.locator('#clear-progress').click();await storagePage.waitForFunction(()=>document.querySelector('#progress-status').textContent.includes('gelöscht'));assert.match(await storagePage.locator('#completed-progress').textContent(),/^0 \/ /);await storageContext.close();
  const faultContext=await browser.newContext();await faultContext.addInitScript(()=>{Object.defineProperty(window,'indexedDB',{value:{open(){throw new DOMException('Simulierter Speicherfehler','SecurityError');}}});Object.defineProperty(navigator,'requestMIDIAccess',{value:undefined,configurable:true});});
  const faultPage=await faultContext.newPage();await faultPage.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});await faultPage.waitForFunction(()=>window.__practice?.engine&&!window.__practice.busy);await faultPage.locator('#step').click();await faultPage.locator('[data-midi="48"]').click();await faultPage.locator('[data-midi="60"]').click();assert.equal(await faultPage.evaluate(()=>window.__practice.engine.beat),1);assert.match(await faultPage.locator('#progress-status').textContent(),/nicht verfügbar/);await faultPage.locator('#midi-settings summary').click(); await faultPage.locator('#midi-connect').click();assert.match(await faultPage.locator('#midi-status').textContent(),/unterstützt MIDI nicht/);await faultContext.close();
  assert.deepEqual(errors,[],'Keine Laufzeitfehler'); console.log('Browser bestanden: komplettes Beispiel, Cursor, Maus/Tastatur/Touch, Audio (30 Samples und Signal), Pause/Tempo/Loops, XML/MXL/Fehlerfälle, Auftakt/Stimmen/Triolen/Taktwechsel, Handwahl, simuliertes MIDI/Trennen, IndexedDB/Neuladen/Löschen/Speicherfehler, Desktop/Mobil.');
} finally { await browser.close(); }
