import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { zipSync, strToU8 } from 'fflate';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1360, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('test-results', { recursive: true });
const state = () => page.evaluate(() => { const a=window.__practice; const e=a.engine; return { busy:a.busy, beat:e?.beat, expected:e?.expected, finished:e?.finished, collected:[...(e?.collected??[])], measures:e?.score.measures, notes:e?.score.notes, playing:e?.playing, mode:e?.mode, settings:e?.settings, title:e?.score.title }; });
const ready = async () => { await page.waitForFunction(() => window.__practice?.engine && !window.__practice.busy, null, {timeout:60000}); };
try {
  await page.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'}); await ready();
  let s=await state(); assert.equal(s.measures.length,8); assert.equal(s.notes[0].midi,60,'MusicXML C4 muss MIDI 60 sein');
  assert.equal(s.measures.at(-1).end,32); assert.equal(s.notes.find(n=>n.start===26 && n.midi===60).end,32,'Haltebogen über Taktgrenze');
  assert.equal(await page.evaluate(()=>window.__practice.view.osmd.cursor.Iterator.CurrentSourceTimestamp.RealValue*4),0,'Cursor am ersten Einsatz');
  assert.equal(await page.locator('#score svg').count()>0,true);
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
  await page.locator('#step').click();
  assert.deepEqual((await state()).expected,[60,48]);
  await page.keyboard.down('a'); assert.deepEqual((await state()).collected,[60]);
  await page.keyboard.down('a'); assert.deepEqual((await state()).collected,[60]);
  await page.keyboard.up('a');
  await page.locator('[data-midi="61"]').click(); assert.equal((await state()).beat,0); assert.deepEqual((await state()).collected,[60]);
  await page.locator('[data-midi="48"]').click(); assert.equal((await state()).beat,1);
  assert.equal(await page.evaluate(()=>window.__practice.view.osmd.cursor.Iterator.CurrentSourceTimestamp.RealValue*4),1,'Cursor folgt dem Schritt');
  let count=0;
  while (!(s=await state()).finished && count++<100) for (const midi of s.expected) await page.locator(`[data-midi="${midi}"]`).click();
  assert.equal((await state()).finished,true,'Gesamtes Beispiel durch Schrittmodus');
  await page.locator('#listen').click(); await page.locator('#play').click();
  await page.waitForFunction(()=>window.__practice.audio.diagnostics.ready && window.__practice.engine.playing);
  assert.deepEqual(await page.evaluate(()=>window.__practice.audio.diagnostics),{ready:true,buffers:30,context:'running'});
  await page.waitForFunction(()=>window.__practice.engine.beat>.3);
  assert.equal(await page.locator('.piano-key.sounding').count()>0,true);
  await page.locator('#play').click(); const paused=(await state()).beat; await page.waitForTimeout(150); assert.equal((await state()).beat,paused);
  await page.locator('#play').click(); await page.waitForFunction(p=>window.__practice.engine.beat>p,paused); await page.locator('#play').click();
  const rms=await page.evaluate(async()=>{const c=new AudioContext(); const b=await c.decodeAudioData(await (await fetch('/piano/C4.mp3')).arrayBuffer());const data=b.getChannelData(0);const value=Math.sqrt(data.reduce((a,x)=>a+x*x,0)/data.length);await c.close();return value;});
  assert.ok(rms>.001,'Klaviersample enthält hörbares Signal');
  await page.locator('#from').selectOption('1'); await page.locator('#to').selectOption('1'); await page.locator('#loop').check(); await page.locator('#step').click();
  const initial=(await state()).beat; let loops=0;
  while(loops++<20){s=await state();for(const midi of s.expected)await page.locator(`[data-midi="${midi}"]`).click(); if((await state()).beat===initial)break;}
  assert.equal((await state()).finished,false); assert.equal((await state()).beat,initial);
  await page.locator('#file').setInputFiles({name:'kaputt.xml',mimeType:'application/xml',buffer:Buffer.from('<kaputt>')});
  await page.waitForFunction(()=>document.querySelector('#message').classList.contains('error')); assert.equal((await state()).title,'Kleine Klavierzeit');
  const example=await readFile('public/example.musicxml');
  const mxl=zipSync({'META-INF/container.xml':strToU8('<container><rootfiles><rootfile full-path="score.musicxml" media-type="application/vnd.recordare.musicxml+xml"/></rootfiles></container>'),'score.musicxml':example});
  await page.locator('#file').setInputFiles({name:'beispiel.mxl',mimeType:'application/vnd.recordare.musicxml',buffer:Buffer.from(mxl)}); await ready(); assert.equal((await state()).measures.length,8);
  await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(250); await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Keine horizontale Seitenausdehnung');
  const touchContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const touchPage=await touchContext.newPage();await touchPage.goto('http://127.0.0.1:5173');await touchPage.waitForFunction(()=>window.__practice?.engine&&!window.__practice.busy);await touchPage.locator('#step').tap();await touchPage.locator('[data-midi="48"]').tap();await touchPage.locator('[data-midi="60"]').tap();assert.equal(await touchPage.evaluate(()=>window.__practice.engine.beat),1);await touchContext.close();
  assert.deepEqual(errors,[],'Keine Laufzeitfehler'); console.log('Browser: Beispiel komplett, Cursor/Noten, Maus/Tastatur/Touch, Audio (30 Samples, Signal), Pause/Fortsetzen, Taktloop, XML/MXL-Import, fehlerhafter Import, Desktop/Mobil bestanden.');
} finally { await browser.close(); }
